MvcCv/Controllers/SertifikaController.cs
using MvcCv.Models.Entity;
using MvcCv.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcCv.Controllers
{
    public class SertifikaController : Controller
    {
        // GET: Sertifika
        GenericReporsitory<TblSertifikalarim> repo = new GenericReporsitory<TblSertifikalarim>();

        public ActionResult Index()
        {
            var certificate = repo.List();
            return View(certificate);
        }


        [HttpGet]
        public ActionResult SertifikaEkle()
        {
            return View();
        }


        [HttpPost]
        public ActionResult SertifikaEkle(TblSertifikalarim certificate)
        {
            if (!ModelState.IsValid)
            {
                return View("SertifikaEkle");
            }
            repo.TAdd(certificate);
            return RedirectToAction("Index");
        }


        public ActionResult SertifikaSil(int id)
        {
            TblSertifikalarim c = repo.Find(x => x.ID == id);
            repo.TDelete(c);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult SertifikaGetir(int id)
        {
            TblSertifikalarim ce = repo.Find(x => x.ID == id);
            return View(ce);
        }

        [HttpPost]
        public ActionResult SertifikaGetir(TblSertifikalarim se)
        {
            if (!ModelState.IsValid)
            {
                return View("SertifikaGetir");
            }
            TblSertifikalarim certificates = repo.Find(x => x.ID == se.ID);
            certificates.Aciklama = se.Aciklama;
            certificates.KursAd = se.KursAd;
            certificates.Teknolojiler = se.Teknolojiler;
            certificates.Tarih = se.Tarih;
            certificates.SertifikaUrl = se.SertifikaUrl;

            repo.TUpdate(certificates);
            return RedirectToAction("Index");
        }

    }
}

MvcCv/Views/Sertifika/Index.cshtml
@using MvcCv.Models.Entity
@model List<TblSertifikalarim>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2 style="text-align: center; font-weight: bold; color: #343a40;">Dinamik CV Sitesi Sertifika Listesi Admin Paneli</h2>
<br />
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <section class="content">
        <div class="container-fluid">
            <div class="row">

                <!-- /.col -->
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header p-2">
                            <br />
                            <a href="/Sertifika/SertifikaEkle/" class="btn btn-success" style="float: right;">Yeni Sertifika Ekle</a>

                            <br />
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            <div class="tab-pane" id="timeline">
                                <!-- The timeline -->
                                <div class="timeline timeline-inverse">
                                    @foreach (var item in Model)
                                    {
                                        <!-- timeline time label -->
                                        <div class="time-label">
                                            <span class="bg-success">
                                                @item.Tarih
                                            </span>
                                        </div>
                                        <!-- /.timeline-label -->
                                        <!-- timeline item -->
                                        <div>
                                            <i class="fas fa-trophy bg-warning"></i>
                                            <div class="timeline-item">
                                                <h3 class="timeline-header"><a href="@item.SertifikaUrl">@item.Aciklama</a> @item.KursAd</h3>
                                                <div class="timeline-body">
                                                    <strong> Kurs ve Sertifika Hakkında Bilgiler ve Kullanılan Teknolojiler: </strong>  @item.Teknolojiler
                                                </div>
                                                <div class="timeline-footer">
                                                    <a href="/Sertifika/SertifikaGetir/@item.ID" class="btn btn-primary btn-sm">Düzenle</a>
                                                    <a href="/Sertifika/SertifikaSil/@item.ID" class="btn btn-danger btn-sm">Sil</a>
                                                </div>
                                            </div>
                                        </div>
                                    }


                                </div>
                            </div>
                        </div>
                        <!-- /.tab-content -->
                    </div><!-- /.card-body -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
</body>
</html>

MvcCv/Views/Sertifika/SertifikaEkle.cshtml
@model MvcCv.Models.Entity.TblSertifikalarim

@{
    ViewBag.Title = "SertifikaEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2 style="text-align: center; font-weight: bold; color: #343a40;">Yeni Sertifika Ekleme Paneli</h2>
<br />
<a href="/Sertifika/Index/" class="btn btn-primary" style="float: right;">Geri Dön</a>

<br />
<form method="post" class="form-group">

    <div class="form-outline mb-4">
        @Html.Label("Sertifika Adı")
        @Html.TextBoxFor(model => model.Aciklama, new { @class = "form-control", placeholder = "Lütfen Sertifika Adı giriniz" })
        @Html.ValidationMessageFor(model => model.Aciklama, "", new { @style = "color: red" })
    </div>

    <div class="form-outline mb-4">
        @Html.Label("Kurum Adı")
        @Html.TextBoxFor(model => model.KursAd, new { @class = "form-control", placeholder = "Lütfen kurum bilgisini giriniz" })
        @Html.ValidationMessageFor(model => model.KursAd, "", new { @style = "color: red" })
    </div>

    <div class="form-outline mb-4">
        @Html.Label("Teknolojiler | Kurs Açıklaması")
        @Html.TextBoxFor(model => model.Teknolojiler, new { @class = "form-control", placeholder = "Lütfen konum bilgisini giriniz" })
        @Html.ValidationMessageFor(model => model.Teknolojiler, "", new { @style = "color: red" })
    </div>

    <div class="form-outline mb-4">
        @Html.Label("Tarih")
        @Html.TextBoxFor(model => model.Tarih, new { @class = "form-control", placeholder = "Lütfen sertifikayı aldığınız tarihi giriniz" })
        @Html.ValidationMessageFor(model => model.Tarih, "", new { @style = "color: red" })
    </div>

    <div class="form-outline mb-4">
        @Html.Label("Sertifika URL")
        @Html.TextBoxFor(model => model.SertifikaUrl, new { @class = "form-control", placeholder = "Lütfen Sertifika linkini giriniz" })
        @Html.ValidationMessageFor(model => model.SertifikaUrl, "", new { @style = "color: red" })
    </div>


    <button data-mdb-ripple-init class="btn btn-success btn-block mb-4">Yeni Sertifikayı Kaydet</button>

</form>

MvcCv/Views/Sertifika/SertifikaGetir.cshtml
@model MvcCv.Models.Entity.TblSertifikalarim

@{
    ViewBag.Title = "SertifikaGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2 style="text-align: center; font-weight: bold; color: #343a40;">Sertifika Güncelleme Paneli</h2>
<br />
<a href="@Url.Action("Index", "Sertifika")" class="btn btn-primary" style="float: right;">Geri Dön</a>

<br />
<form method="post">

    <div class="form-outline mb-4">
        @Html.Label("Sertifika Adı")
        @Html.TextBoxFor(model => model.Aciklama, new { @class = "form-control", placeholder = "Lütfen Sertifika Adı giriniz" })
        @Html.ValidationMessageFor(model => model.Aciklama, "", new { @style = "color: red" })
    </div>

    <div class="form-outline mb-4">
        @Html.Label("Kurum Adı")
        @Html.TextBoxFor(model => model.KursAd, new { @class = "form-control", placeholder = "Lütfen kurum bilgisini giriniz" })
        @Html.ValidationMessageFor(model => model.KursAd, "", new { @style = "color: red" })
    </div>

    <div class="form-outline mb-4">
        @Html.Label("Teknolojiler | Kurs Açıklaması")
        @Html.TextBoxFor(model => model.Teknolojiler, new { @class = "form-control", placeholder = "Lütfen konum bilgisini giriniz" })
        @Html.ValidationMessageFor(model => model.Teknolojiler, "", new { @style = "color: red" })
    </div>

    <div class="form-outline mb-4">
        @Html.Label("Tarih")
        @Html.TextBoxFor(model => model.Tarih, new { @class = "form-control", placeholder = "Lütfen sertifikayı aldığınız tarihi giriniz" })
        @Html.ValidationMessageFor(model => model.Tarih, "", new { @style = "color: red" })
    </div>

    <div class="form-outline mb-4">
        @Html.Label("Sertifika URL")
        @Html.TextBoxFor(model => model.SertifikaUrl, new { @class = "form-control", placeholder = "Lütfen Sertifika linkini giriniz" })
        @Html.ValidationMessageFor(model => model.SertifikaUrl, "", new { @style = "color: red" })
    </div>


    <!-- Submit button -->
    <button class="btn btn-success btn-block mb-4">Değişiklikleri Kaydet</button>
</form>